[book]
authors = ["Peter Robinson"]
language = "en"
multilingual = false
src = "src"
title = "GA4GH Phenoboard"
numbered = false

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"